[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
